# -*- coding: utf-8 -*-
import doctest

"""CPSC 442 – Assignment #2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18gn6nXPcz58jF6zgkBYQCoEQ5biZ_1-K
"""

#Source: https://stackoverflow.com/questions/2748564/doctesting-functions-that-receive-and-display-user-input-python-tearing-my-ha
def test_input_generator(*args):
    """Creates test input function that reads inputs from the passed arguments.
    This is used to override input to allow doctests to mimic user
    input

    Returns:
        function: this function is meant to moc out input and each time it is
                  called it will print the supplied prompt along with the "input"
                  supplied at the time the function was created.
    """
    input_iterator = (test_input for test_input in args)

    def test_input(prompt):
        """Gets input from outer input_iterator and prints the supplied
        prompt along with the test input.

        Args:
            prompt :  the prompt ot display to the user

        Returns:
            str:  the test input string
        """
        response = next(input_iterator)
        print(f"{prompt}{response}")
        return response

    return test_input

"""**Problem 1:** Write a program to compute the grades of students. The test scores are to be read from a text file. Using notepad, create a comma separated file with the data in it. Note that the data contains:

*firstname,lastname,id,test1,test2,final*

Bill,Bakar,11452,85,83,84

Sally,Simpson,11157,88,92,95

Mark,Mathews,111932,77,75,78

Cindy,Williams,1117,65,71,81

John,Jacobs,111873,67,72,68

Amy,Albright,11262,91,95,92

The weight of the test is 30%, the weight for the second test is 30%, and the weight for the final is 40%. The grades breakown is:

`>` 90% A

85% - 89.99% A-

80% - 84.99% B+

70% - 79.99% B

60% - 69.99% C

50% - 59.99% D

The computed grades are to be stored in an output file as:

id    last name    grade
"""

# >>> compute_grades(inputFileName, outputFileName)
# (-2.0, -3.0)
def compute_grades(inputFileName, outputFileName):
  """Reads marks of students and compute their grades and write the result to an output file.

  Examples:
  >>> compute_grades(inputFileName=test_input_generator('final_grades.txt'), outputFileName=test_input_generator('result_grades.txt'))
  
  """ 
  f = open(inputFileName, 'r')
  results = []
  for line in f:
    toList = [item.strip() for item in str.split(line, ',') if item]
    # toList[3] = int(toList[3])
    # toList[4] = int(toList[4])
    # toList[5] = int(toList[5])
    score = (30/100 * int(toList[3])) + (30/100 * int(toList[4])) + (40/100 * int(toList[5]))
    grade = 'D'
    if(score > 90):
      grade = 'A'
    elif(85<=score and score <=89.99):
      grade = 'A-'
    elif(80<=score and score <=84.99):
      grade = 'B+'
    elif(70<=score and score <=79.99):
      grade = 'B'
    elif(60<=score and score <=69.99):
      grade = 'C'      
    elif(50<=score and score <=59.99):
      grade = 'D'
    else:
      grade = 'F'

    results.append(toList[2]+"    "+toList[1]+"    "+grade)

  f.close()

  fw = open(outputFileName, 'a')

  for result in results:
    fw.write(result+'\n')
  fw.close()



# f = open (‘myfile.txt’, 'a')
# f.write(‘\nThis sentence will be appended.’)

"""**Problem 2:** Write a program to compute the pay of Employees. The data is to be read from a file as:

*first name,last name,employee id,hours worked,pay rate*

Adam,Ames,111452,45,17.50

Sally,Sims,111657,35,22.75

Mark,Manning,111932,52,16.50

Cindy,Carson,1117,48,18.50

Jim,Jacobs,111873,38,25

Alice,Andrews,11262,60,19.50

You will write a function called compute_pay that will compute the pay of the employee. The pay is to be computed as hours worked multiplied by the pay rate if the number of hours worked is less than 40. If the number of hours worked is greater than 40, then the pay has to be 

1.75`*`pay_rate`*`hours_worked.

The computed pay is to be stored in an output file as:

id    last name    pay
"""

# >>> compute_pay(inputFileName, outputFileName)
# (-2.0, -3.0)
def compute_pay(inputFileName, outputFileName):
  """
    Reads hours worked by employees from a file, compute their pay and write the result to an output file.
  """ 
  f = open(inputFileName, 'r')
  salaries = []
  for line in f:
    toList = [item.strip() for item in str.split(line, ',') if item]
    # toList[3] = int(toList[3])
    # toList[4] = int(toList[4])
    salary = 0
    if(float(toList[3])<40):
      salary = float(toList[3])*(float(toList[4])/100)
    elif(float(toList[3])>=40):
      salary = 1.75*float(toList[3])*(float(toList[4])/100)

    salaries.append(str(toList[2])+"    "+str(toList[1])+"    "+str(salary))

  f.close()

  fw = open(outputFileName, 'a')

  for result in salaries:
    fw.write(result+'\n')
  fw.close()


# call the testmod function
if __name__ == '__main__':
    # doctest.testmod(verbose = True)
  print("Running Problem 1")
  compute_grades('final_grades.txt', 'result_grades.txt')
  print("Done! output saved as result_grades.txt")

  print("Running Problem 2")
  compute_pay('employee_pays.txt', 'result_pays.txt')
  print("Done! output saved as result_pays.txt")